### ISSUE TITLE
Cannot create a file with a single header at level 2 (without having a level 1)

### ISSUE THREAD

**Issue by rougier** [didix21/mdutils#69]
**Describe the bug**
Cannot create a file with a single header at level 2 (without having a level 1)

**To Reproduce**

```
from mdutils.mdutils import MdUtils
mdFile = MdUtils(file_name='example.md',title='Markdown File Example')
mdFile.new_header(level=2, title='Atx Header 2')
mdFile.create_md_file()
```

**Expected behavior**
Markdown file with a level 2 header

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: Python 3.8, mdutils installed throurgh pip

**Additional context**

Traceback:
```
Traceback (most recent call last):
  File "test-mdutils.py", line 4, in <module>
    mdFile.new_header(level=2, title='Atx Header 2')
  File "/opt/anaconda3/lib/python3.8/site-packages/mdutils/mdutils.py", line 113, in new_header
    self.__add_new_item_table_of_content(level, title)
  File "/opt/anaconda3/lib/python3.8/site-packages/mdutils/mdutils.py", line 130, in __add_new_item_table_of_content
    curr = curr[-1]
IndexError: list index out of range
```

**Comment by GoodmanBen** [comment]
If you are okay with the header not being included in the table of contents, a work around to have the code run is to set  `add_table_of_contents="n"`, then the code should run without error (although possibly not with the fully desired behavior).
```
mdFile.new_header(level=2, title='Atx Header 2', add_table_of_contents="n")
```
